In [1]:
import pandas as pd
import numpy as np

c:\Users\chado\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [5]:
df1 = pd.read_csv('step1_df_2.csv', index_col = 0)
df2 = pd.read_csv('step1_df.csv',index_col = 0)
df3 = pd.read_csv('counts.csv', index_col = 0)

In [6]:
df1.head()

,listing_url,brand,model,year,fuel_type,transmission,body_type,engine_capacity,scraped_at
0,https://www.dubizzle.com.eg/en/ad/%D8%A8%D9%89...,BYD,Song Plus,2025,Electric,Automatic,SUV,NaN,2026-01-30 18:09:21
1,https://www.dubizzle.com.eg/en/ad/audi-a5-2019...,Audi,A5,2019,Benzine,Automatic,Sedan,NaN,2026-01-30 18:09:41
2,https://www.dubizzle.com.eg/en/ad/%D8%B4%D9%8A...,Chery,Tiggo 8,2022,Benzine,Automatic,SUV,1500.0,2026-01-30 18:10:03
3,https://www.dubizzle.com.eg/en/ad/%D9%85%D9%8A...,Mitsubishi,Lancer,1997,Benzine,Automatic,Sedan,1300.0,2026-01-30 18:10:16
4,https://www.dubizzle.com.eg/en/ad/%D9%87%D9%8A...,Hyundai,Elantra,2026,Benzine,Automatic,Sedan,1500.0,2026-01-30 18:10:33

In [7]:
df2.head()

,listing_url,brand,model,year,fuel_type,transmission,body_type,engine_capacity,scraped_at
0,https://www.dubizzle.com.eg/en/ad/%D8%A8%D9%8A...,BMW,523,1999.0,Benzine,Automatic,Sedan,2500.0,2026-01-16 21:04:24
1,https://www.dubizzle.com.eg/en/ad/%D9%87%D9%8A...,Hyundai,Elantra,2026.0,Benzine,Automatic,Sedan,NaN,2026-01-16 21:04:33
2,https://www.dubizzle.com.eg/en/ad/%D9%81%D9%88...,Volkswagen,Golf,2010.0,Benzine,Automatic,Hatchback,1400.0,2026-01-16 21:04:45
3,https://www.dubizzle.com.eg/en/ad/citroen-ds4-...,Citroen,DS4,2023.0,Benzine,Automatic,Hatchback,1600.0,2026-01-16 21:04:59
4,https://www.dubizzle.com.eg/en/ad/%D9%87%D9%8A...,Hyundai,Elantra,2026.0,Benzine,Automatic,Sedan,1600.0,2026-01-16 21:05:08

In [9]:
df2.count()

listing_url        6716
brand              6672
model              6672
year               6672
fuel_type          6681
transmission       6681
body_type          6677
engine_capacity    4791
scraped_at         6716
dtype: int64

In [10]:
df2.groupby(['brand', 'model', 'year', 'fuel_type', 'transmission', 'body_type', 'engine_capacity']).size().reset_index(name='count').sort_values(by = 'count', ascending=False)

,brand,model,year,fuel_type,transmission,body_type,engine_capacity,count
1628,Mercedes-Benz,E200,2026.0,Benzine,Automatic,Sedan,2000.0,24
1973,Opel,Vectra,2008.0,Benzine,Automatic,Sedan,1600.0,20
1699,Mercedes-Benz,GLC 300,2026.0,Benzine,Automatic,SUV,2000.0,18
1873,Nissan,Sunny,2026.0,Benzine,Automatic,Sedan,1500.0,16
1626,Mercedes-Benz,E200,2025.0,Benzine,Automatic,Sedan,2000.0,15
...,...,...,...,...,...,...,...,...
1071,Hyundai,Verna,2007.0,Benzine,Manual,Other,1600.0,1
1070,Hyundai,Verna,2007.0,Benzine,Automatic,Sedan,1600.0,1
1069,Hyundai,Verna,2004.0,Natural Gas,Manual,Sedan,1600.0,1
1067,Hyundai,Verna,2004.0,Benzine,Automatic,Sedan,100.0,1
2690,Zotye,Explosion,2009.0,Natural Gas,Manual,Hatchback,1600.0,1

In [14]:
df = df2.groupby(['brand', 'model', 'year', 'fuel_type', 'transmission', 'body_type', 'engine_capacity'])

In [15]:
df.count()

                                                                                  listing_url  \
brand        model     year   fuel_type   transmission body_type engine_capacity
Alfa Romeo   156       2002.0 Benzine     Manual       Sedan     2000.0                     1
             Stelvio   2020.0 Benzine     Automatic    SUV       2000.0                     2
             Tonale    2024.0 Benzine     Automatic    SUV       2000.0                     1
                       2025.0 Benzine     Automatic    SUV       2000.0                     2
Aston Martin DB        2025.0 Benzine     Automatic    SUV       3982.0                     1
...                                                                                       ...
Xiaomi       YU7       2025.0 Electric    Automatic    SUV       1000.0                     1
Zeekr        7X        2025.0 Electric    Automatic    SUV       310.0                      2
Zotye        Explosion 2008.0 Benzine     Manual       SUV       1300.0                     1
                                                                 1600.0                     1
                       2009.0 Natural Gas Manual       Hatchback 1600.0                     1

                                                                                  scraped_at
brand        model     year   fuel_type   transmission body_type engine_capacity
Alfa Romeo   156       2002.0 Benzine     Manual       Sedan     2000.0                    1
             Stelvio   2020.0 Benzine     Automatic    SUV       2000.0                    2
             Tonale    2024.0 Benzine     Automatic    SUV       2000.0                    1
                       2025.0 Benzine     Automatic    SUV       2000.0                    2
Aston Martin DB        2025.0 Benzine     Automatic    SUV       3982.0                    1
...                                                                                      ...
Xiaomi       YU7       2025.0 Electric    Automatic    SUV       1000.0                    1
Zeekr        7X        2025.0 Electric    Automatic    SUV       310.0                     2
Zotye        Explosion 2008.0 Benzine     Manual       SUV       1300.0                    1
                                                                 1600.0                    1
                       2009.0 Natural Gas Manual       Hatchback 1600.0                    1

[2691 rows x 2 columns]

In [18]:
df = df2.drop_duplicates(['brand', 'model', 'year', 'fuel_type', 'transmission', 'body_type', 'engine_capacity'])

In [19]:
df.count()

listing_url        3798
brand              3788
model              3788
year               3788
fuel_type          3797
transmission       3797
body_type          3793
engine_capacity    2691
scraped_at         3798
dtype: int64

In [26]:
df.isnull().sum()

listing_url          0
brand               10
model               10
year                10
fuel_type            1
transmission         1
body_type            5
engine_capacity    613
scraped_at           0
dtype: int64

In [24]:
cols = ["brand", "model", "year", "fuel_type", "transmission", "body_type"]

check = (
    df
    .groupby(cols)["engine_capacity"]
    .agg([
        lambda x: x.isna().any(),        # has_null
        lambda x: x.notna().any()        # has_non_null
    ])
)

check.columns = ["has_null", "has_non_null"]

# combinations that have BOTH
problematic = check[(check["has_null"]) & (check["has_non_null"])]

problematic

                                                           has_null  \
brand      model  year   fuel_type transmission body_type
Alfa Romeo 156    2002.0 Benzine   Manual       Sedan          True
Audi       Q3     2021.0 Benzine   Automatic    SUV            True
                  2025.0 Benzine   Automatic    SUV            True
           Q7     2022.0 Benzine   Automatic    SUV            True
                  2025.0 Benzine   Automatic    SUV            True
...                                                             ...
Volkswagen Tiguan 2026.0 Benzine   Automatic    Estate         True
                                                SUV            True
Xiaomi     SU7    2025.0 Electric  Automatic    Sedan          True
           YU7    2025.0 Electric  Automatic    SUV            True
Zeekr      7X     2025.0 Electric  Automatic    SUV            True

                                                           has_non_null
brand      model  year   fuel_type transmission body_type
Alfa Romeo 156    2002.0 Benzine   Manual       Sedan              True
Audi       Q3     2021.0 Benzine   Automatic    SUV                True
                  2025.0 Benzine   Automatic    SUV                True
           Q7     2022.0 Benzine   Automatic    SUV                True
                  2025.0 Benzine   Automatic    SUV                True
...                                                                 ...
Volkswagen Tiguan 2026.0 Benzine   Automatic    Estate             True
                                                SUV                True
Xiaomi     SU7    2025.0 Electric  Automatic    Sedan              True
           YU7    2025.0 Electric  Automatic    SUV                True
Zeekr      7X     2025.0 Electric  Automatic    SUV                True

[494 rows x 2 columns]

In [25]:
## Filling null engines with median

cols = ["brand", "model", "year", "fuel_type", "transmission", "body_type"]

df["engine_capacity"] = (
    df.groupby(cols)["engine_capacity"]
      .transform(lambda x: x.fillna(x.median()))
)

c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\chado\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

In [27]:
df = df.drop_duplicates(['brand', 'model', 'year', 'fuel_type', 'transmission', 'body_type', 'engine_capacity'])

In [29]:
cols = ["brand", "model", "year", "fuel_type", "transmission", "body_type"]

validation = (
    df
    .groupby(cols)["engine_capacity"]
    .agg(has_null=lambda x: x.isna().any(),
         has_non_null=lambda x: x.notna().any())
)

# combinations that still have both
problematic = validation[
    (validation["has_null"]) & (validation["has_non_null"])
]

problematic

Empty DataFrame
Columns: [has_null, has_non_null]
Index: []

In [ ]:
## Converting year column to integer
df["year"] = df["year"].replace([np.inf, -np.inf], np.nan).astype("Int64")

In [23]:
df['year'].dtype

Int64Dtype()

In [24]:
cols = ["brand", "model", "year", "fuel_type",
        "transmission", "body_type", "engine_capacity"]

df["vehicle_id"] = (
    df[cols]
    .astype(str)
    .agg("_".join, axis=1)
)

df = df.set_index("vehicle_id")

In [26]:
df

,brand,model,year,fuel_type,transmission,body_type,engine_capacity,scraped_at
vehicle_id,,,,,,,,
BMW_523_1999_Benzine_Automatic_Sedan_2500.0,BMW,523,1999,Benzine,Automatic,Sedan,2500.0,2026-01-16 21:04:24
Hyundai_Elantra_2026_Benzine_Automatic_Sedan_1550.0,Hyundai,Elantra,2026,Benzine,Automatic,Sedan,1550.0,2026-01-16 21:04:33
Volkswagen_Golf_2010_Benzine_Automatic_Hatchback_1400.0,Volkswagen,Golf,2010,Benzine,Automatic,Hatchback,1400.0,2026-01-16 21:04:45
Citroen_DS4_2023_Benzine_Automatic_Hatchback_1600.0,Citroen,DS4,2023,Benzine,Automatic,Hatchback,1600.0,2026-01-16 21:04:59
Hyundai_Elantra_2026_Benzine_Automatic_Sedan_1600.0,Hyundai,Elantra,2026,Benzine,Automatic,Sedan,1600.0,2026-01-16 21:05:08
...,...,...,...,...,...,...,...,...
Geely_Ck2_2009_Benzine_Manual_Sedan_1500.0,Geely,Ck2,2009,Benzine,Manual,Sedan,1500.0,2026-01-30 19:44:59
Volkswagen_Tiguan_2026_Benzine_Automatic_Hatchback_1400.0,Volkswagen,Tiguan,2026,Benzine,Automatic,Hatchback,1400.0,2026-01-30 19:46:21
Chevrolet_Cruze_2009_Benzine_Automatic_Sedan_1600.0,Chevrolet,Cruze,2009,Benzine,Automatic,Sedan,1600.0,2026-01-30 19:46:46
BMW_IX1_2020_Benzine_Automatic_SUV_1500.0,BMW,IX1,2020,Benzine,Automatic,SUV,1500.0,2026-01-30 19:47:45
Proton_Wira_2004_Diesel_Manual_Sedan_1300.0,Proton,Wira,2004,Diesel,Manual,Sedan,1300.0,2026-01-30 19:47:58

In [27]:
df.to_csv('Cars_type.csv')

In [35]:
df = df.drop('listing_url', axis = 1)
df

,brand,model,year,fuel_type,transmission,body_type,engine_capacity,scraped_at
vehicle_id,,,,,,,,
a20e6f21ad0ea4d3c19326668df1fb47,BMW,523,1999.0,Benzine,Automatic,Sedan,2500.0,2026-01-16 21:04:24
b119f59bbb1786077d9f116a8b060202,Hyundai,Elantra,2026.0,Benzine,Automatic,Sedan,1550.0,2026-01-16 21:04:33
f1c7ecc99cd4ca220b9d2d23d40d766e,Volkswagen,Golf,2010.0,Benzine,Automatic,Hatchback,1400.0,2026-01-16 21:04:45
4ba84841572787eb6844c7432f0521b2,Citroen,DS4,2023.0,Benzine,Automatic,Hatchback,1600.0,2026-01-16 21:04:59
34147509b62de91f1fd2bcff74e23f8b,Hyundai,Elantra,2026.0,Benzine,Automatic,Sedan,1600.0,2026-01-16 21:05:08
...,...,...,...,...,...,...,...,...
3f653daf6fa9062601b940046a041846,Geely,Ck2,2009.0,Benzine,Manual,Sedan,1500.0,2026-01-30 19:44:59
fb77f190217ed76af88f780ccfbaf245,Volkswagen,Tiguan,2026.0,Benzine,Automatic,Hatchback,1400.0,2026-01-30 19:46:21
15e29107f470854ce289f01bf7fbf879,Chevrolet,Cruze,2009.0,Benzine,Automatic,Sedan,1600.0,2026-01-30 19:46:46
c090e23d203be8e636d0240136c3a412,BMW,IX1,2020.0,Benzine,Automatic,SUV,1500.0,2026-01-30 19:47:45
fdef57465b4b7be5ef083374d8ca34d0,Proton,Wira,2004.0,Diesel,Manual,Sedan,1300.0,2026-01-30 19:47:58

In [39]:
df.to_csv('Cars_type.csv')

## Body type standardization

In [65]:

df.loc[
    df["body_type"].str.contains(
        r"small city car|\.minimize|capitalize",
        case=False,
        na=False
    ),
    "body_type"
] = "Hatchback"

# 4X4
df.loc[
    df["body_type"].str.contains(r"4x4|4wd|awd|off.?road", case=False, na=False),
    "body_type"
] = "4X4"

# Sports / Coupe
df.loc[
    df["body_type"].str.contains(r"sport|coupe", case=False, na=False),
    "body_type"
] = "Sports / Coupe"

# Sedan
df.loc[
    df["body_type"].str.contains(r"sedan|saloon", case=False, na=False),
    "body_type"
] = "Sedan"

# Van / Bus
df.loc[
    df["body_type"].str.contains(r"van|bus|minibus|mpv", case=False, na=False),
    "body_type"
] = "Van / Bus"

df.loc[df["body_type"] == "4X4", "body_type"] = "SUV"

df = df[df["body_type"] != "Other"]

In [66]:
df['body_type'].value_counts()

body_type
Sedan             1603
SUV                786
Hatchback          661
Sports / Coupe      93
Van / Bus           73
Estate              66
Pickup              43
Convertible         41
Name: count, dtype: int64

## convert floats to integers

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3371 entries, a20e6f21ad0ea4d3c19326668df1fb47 to fdef57465b4b7be5ef083374d8ca34d0
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   brand            3361 non-null   object
 1   model            3361 non-null   object
 2   year             3361 non-null   float64
 3   fuel_type        3370 non-null   object
 4   transmission     3370 non-null   object
 5   body_type        3366 non-null   object
 6   engine_capacity  2770 non-null   float64
 7   scraped_at       3371 non-null   object
dtypes: float64(2), object(6)
memory usage: 237.0+ KB

In [ ]:
df["year"] = df["year"].astype('Int64')

C:\Users\chado\AppData\Local\Temp\ipykernel_25200\1202879175.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["year"] = df["year"].astype('Int64')

In [73]:
df.to_csv('Cars_type.csv')