In [1]:
import pandas as pd

C:\Users\chado\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [3]:
df = pd.read_csv('step1_df.csv')
df.head(20)

,Unnamed: 0,listing_url,brand,model,year,fuel_type,transmission,body_type,engine_capacity,scraped_at
0,0,https://www.dubizzle.com.eg/en/ad/%D8%A8%D9%8A...,BMW,523,1999.0,Benzine,Automatic,Sedan,2500.0,2026-01-16 21:04:24
1,1,https://www.dubizzle.com.eg/en/ad/%D9%87%D9%8A...,Hyundai,Elantra,2026.0,Benzine,Automatic,Sedan,NaN,2026-01-16 21:04:33
2,2,https://www.dubizzle.com.eg/en/ad/%D9%81%D9%88...,Volkswagen,Golf,2010.0,Benzine,Automatic,Hatchback,1400.0,2026-01-16 21:04:45
3,3,https://www.dubizzle.com.eg/en/ad/citroen-ds4-...,Citroen,DS4,2023.0,Benzine,Automatic,Hatchback,1600.0,2026-01-16 21:04:59
4,4,https://www.dubizzle.com.eg/en/ad/%D9%87%D9%8A...,Hyundai,Elantra,2026.0,Benzine,Automatic,Sedan,1600.0,2026-01-16 21:05:08
5,5,https://www.dubizzle.com.eg/en/ad/renault-flue...,Renault,Fluence,2014.0,Benzine,Automatic,Sedan,1600.0,2026-01-16 21:05:16
6,6,https://www.dubizzle.com.eg/en/ad/bmw-x6-m60-2...,BMW,X6,2025.0,Benzine,Automatic,4X4,4000.0,2026-01-16 21:05:26
7,7,https://www.dubizzle.com.eg/en/ad/%D8%A8%D9%8A...,BMW,320,2016.0,Benzine,Automatic,Sedan,2000.0,2026-01-16 21:05:41
8,8,https://www.dubizzle.com.eg/en/ad/chevrolet-av...,Chevrolet,Aveo,2015.0,Benzine,Automatic,Sedan,NaN,2026-01-16 21:05:52
9,9,https://www.dubizzle.com.eg/en/ad/%D8%B9%D8%B1...,Fiat,131,1979.0,Natural Gas,Manual,Sedan,1300.0,2026-01-16 21:06:00
10,10,https://www.dubizzle.com.eg/en/ad/%D8%A8%D9%8A...,Peugeot,3008,2025.0,Benzine,Automatic,SUV,1600.0,2026-01-16 21:06:14
11,11,https://www.dubizzle.com.eg/en/ad/toyota-corol...,Toyota,Corolla,2021.0,Benzine,Automatic,Sedan,NaN,2026-01-16 21:06:28
12,12,https://www.dubizzle.com.eg/en/ad/%D9%81%D9%88...,Volkswagen,Polo,2001.0,Benzine,Manual,Sedan,1400.0,2026-01-16 21:06:35
13,13,https://www.dubizzle.com.eg/en/ad/%D9%87%D8%A7...,Haval,H6,2026.0,Benzine,Automatic,SUV,1500.0,2026-01-16 21:06:44
14,14,https://www.dubizzle.com.eg/en/ad/%D9%83%D9%8A...,Kia,Sportage,2019.0,Benzine,Automatic,SUV,NaN,2026-01-16 21:06:54
15,15,https://www.dubizzle.com.eg/en/ad/peugeot-3008...,Peugeot,3008,2023.0,Benzine,Automatic,SUV,1600.0,2026-01-16 21:07:12
16,16,https://www.dubizzle.com.eg/en/ad/%D8%A8%D9%8A...,Peugeot,406,1998.0,Benzine,Manual,Sedan,1600.0,2026-01-16 21:07:19
17,17,https://www.dubizzle.com.eg/en/ad/skoda-octavi...,Skoda,Octavia,2018.0,Benzine,Automatic,Sedan,1600.0,2026-01-16 21:07:28
18,18,https://www.dubizzle.com.eg/en/ad/%D8%B4%D9%8A...,Chevrolet,Optra,2008.0,Benzine,Automatic,Sedan,1600.0,2026-01-16 21:07:46
19,19,https://www.dubizzle.com.eg/en/ad/%D8%B1%D9%8A...,Renault,Logan,2009.0,Benzine,Manual,Sedan,NaN,2026-01-16 21:07:54

In [24]:
df.info

<bound method DataFrame.info of       Unnamed: 0                                        listing_url  \
0              0  https://www.dubizzle.com.eg/en/ad/%D8%A8%D9%8A...
1              1  https://www.dubizzle.com.eg/en/ad/%D9%87%D9%8A...
2              2  https://www.dubizzle.com.eg/en/ad/%D9%81%D9%88...
3              3  https://www.dubizzle.com.eg/en/ad/citroen-ds4-...
4              4  https://www.dubizzle.com.eg/en/ad/%D9%87%D9%8A...
...          ...                                                ...
3399        3399  https://www.dubizzle.com.eg/en/ad/mercedes-ben...
3400        3400  https://www.dubizzle.com.eg/en/ad/%D8%B3%D9%8A...
3401        3401  https://www.dubizzle.com.eg/en/ad/mercedes-c18...
3402        3402  https://www.dubizzle.com.eg/en/ad/2026-%D8%A8%...
3403        3403  https://www.dubizzle.com.eg/en/ad/mercedes-ben...

              brand     model    year fuel_type transmission  body_type  \
0               BMW       523  1999.0   Benzine    Automatic      Sedan
1           Hyundai   Elantra  2026.0   Benzine    Automatic      Sedan
2        Volkswagen      Golf  2010.0   Benzine    Automatic  Hatchback
3           Citroen       DS4  2023.0   Benzine    Automatic  Hatchback
4           Hyundai   Elantra  2026.0   Benzine    Automatic      Sedan
...             ...       ...     ...       ...          ...        ...
3399  Mercedes-Benz      C200  2026.0   Benzine    Automatic      Sedan
3400         Senova        A1  2016.0   Benzine    Automatic      Sedan
3401  Mercedes-Benz      C180  2022.0   Benzine    Automatic      Sedan
3402        Peugeot      2008  2026.0   Benzine    Automatic        SUV
3403  Mercedes-Benz  A 35 AMG  2024.0   Benzine    Automatic      Sedan

      engine_capacity           scraped_at
0              2500.0  2026-01-16 21:04:24
1                 NaN  2026-01-16 21:04:33
2              1400.0  2026-01-16 21:04:45
3              1600.0  2026-01-16 21:04:59
4              1600.0  2026-01-16 21:05:08
...               ...                  ...
3399           1500.0  2026-01-17 15:06:02
3400              NaN  2026-01-17 15:06:31
3401              NaN  2026-01-17 15:06:52
3402              NaN  2026-01-17 15:07:21
3403           2000.0  2026-01-17 15:07:42

[3404 rows x 10 columns]>

In [18]:
df.groupby(['brand','model']).size().reset_index()

            brand      model   0
0      Alfa Romeo        156   1
1      Alfa Romeo     Tonale   1
2    Aston Martin         DB   1
3            Audi         A3  10
4            Audi         A4   8
..            ...        ...  ..
576         Zeekr        001   1
577         Zeekr        007   1
578         Zeekr         7X   7
579         Zeekr          X   1
580         Zotye  Explosion   1

[581 rows x 3 columns]

In [29]:
df[['brand','model']].value_counts().reset_index().sort_values(by = 'count', ascending = False).head(10)

           brand     model  count
0  Mercedes-Benz      C180    122
1         Nissan     Sunny     58
2            Kia  Sportage     55
3  Mercedes-Benz      E200     50
4  Mercedes-Benz      C200     48
5         Toyota   Corolla     47
6      Chevrolet     Optra     45
7        Renault     Logan     44
8  Mercedes-Benz   GLC 300     42
9         Daewoo     Lanos     42

In [30]:
df[['brand']].value_counts().reset_index().sort_values(by = 'count', ascending = False).head(10)

           brand  count
0  Mercedes-Benz    463
1        Hyundai    199
2            BMW    195
3            Kia    167
4           Fiat    152
5        Renault    150
6      Chevrolet    150
7           Opel    123
8     Volkswagen    115
9         Nissan    114

In [31]:
df[['model']].value_counts().reset_index().sort_values(by = 'count', ascending = False).head(10)

      model  count
0      C180    122
1     Lanos     82
2     Sunny     58
3  Sportage     55
4      E200     50
5      C200     48
6   Corolla     47
7     Optra     45
8     Logan     44
9   GLC 300     42

In [32]:
df[['year']].value_counts().reset_index().sort_values(by = 'count', ascending = False).head(10)

     year  count
0  2026.0    472
1  2025.0    360
2  2024.0    214
3  2022.0    163
4  2020.0    157
5  2021.0    156
6  2019.0    147
7  2023.0    123
8  2015.0    111
9  2008.0    103

In [33]:
df[['body_type']].value_counts().reset_index().sort_values(by = 'count', ascending = False).head(10)

        body_type  count
0           Sedan   1744
1             SUV    758
2       Hatchback    473
3             4X4    122
4  Sports / Coupe     88
5          Estate     48
6       Van / Bus     34
7     Convertible     30
8          Pickup     27
9             MPV     18